name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        type: environment

jobs:
  deploy:
    name: Deploy ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Hello
        run: echo World