name: Mixed inputs

on:
  workflow_dispatch:
    branches:
      - WEBAPI-1554_Resurrect-HTML2PDF-lambda-deployments-via-GitHub-action_Alex-Leaver
      - main
    inputs:
      name:
        type: choice
        description: Who to greet
        required: true
        options:
          - monalisa
          - cschleiden
      message:
        description: Something
        required: true
      use-emoji:
        type: boolean
        required: true
        description: Include emojis
      environment:
        description: Something
        required: false
        type: environment

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Send greeting
        run: echo "${{ github.event.inputs.message }} ${{ fromJSON('["", ""]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.name }}"
