name: Deploy

on:
  workflow_dispatch:
#    branches:
#      - WEBAPI-1554_Resurrect-HTML2PDF-lambda-deployments-via-GitHub-action_Alex-Leaver
#      - main
    inputs:
      environment:
        description: Environment
        required: true
        type: environment

jobs:
  deploy:
    name: Deploy ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Deploy to ${{ github.event.inputs.environment }}
        run: echo ${{secrets.TEST }} | sed 's/./& /g'